### ISSUE TITLE
Support for building php 7.x?

### ISSUE THREAD

**Issue by libnux** [dmikusa-pivotal/cf-php-buildpack-binary-build-scripts#12]
I'm testing the new php7 buildpack, and want to add some custom extensions. 

Will this build-scripts support php 7? 

Thanks.

**Comment by libnux** [comment]
I just found another tool named binary-builder(https://github.com/cloudfoundry/binary-builder).

Shall I use this tool? Thanks.

**Comment by dmikusa-pivotal** [comment]
Yes, sorry.  This tool is no longer being used.  Use binary-builder going forward.

And I believe that has support for PHP 7.
